QuesCheetah/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_view


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^password/reset/done/$', auth_view.password_reset_done, name='password_reset_done'),
    url(r'^password/reset/$', auth_view.password_reset, name='password_reset'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)', auth_view.password_reset_confirm, name='password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$', auth_view.password_reset_complete, name='password_reset_complete'),

    url(r'^accounts/', include('allauth.urls')),

    url(r'v1/', include('vote.urls', namespace='v1')),
    url(r'', include('main.urls', namespace='main')),


]

main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.user_login, name='user_login'),
    url(r'^logout$', views.user_logout, name='user_logout'),
    url(r'^signup$', views.user_signup, name='user_signup'),
    url(r'^user/(?P<id>\w+)', views.user_mypage, name='user_mypage'),
    url(r'^apikey/(?P<key>\w+)/secret', views.secret_key_new, name='secret_key_new'),
    url(r'^apikey/new', views.apikey_new, name='apikey_new'),
    url(r'^domain/new', views.domain_new, name='domain_new'),
    url(r'^domain/delete', views.domain_delete, name='domain_delete'),
    url(r'^jwt/new', views.jwt_new, name='jwt_new'),

    url(r'^downloads', views.downloads, name='downloads'),
]

vote/urls.py
# 직접 개발한 코드
from django.conf.urls import url
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import condition
from vote import views
import datetime

urlpatterns = [

    # QuesCheetah Web Server URLS

    url(r'^select$', views.select_question, name='select_question'),
    url(r'^new/(?P<api_key>\w+)$', views.new, name='new'),

    # Dashboard management URLS

    url(r'dashboard/sample/(?P<page>\w+)$', views.dashboard_sample, name='dashboard_sample'),
    url(r'dashboard/select$', views.dashboard_select, name='dashboard_select'),
    url(r'dashboard/groups/(?P<group_id>\w+)/overview$', views.dashboard_render, name='dashboard_group_overview'),
    url(r'dashboard/(?P<question_id>\w+)/overview$', views.dashboard_render, name='dashboard_overview'),
    url(r'dashboard/groups/(?P<group_id>\w+)/filter$', views.dashboard_render, name='dashboard_group_filter'),
    url(r'dashboard/(?P<question_id>\w+)/filter$', views.dashboard_render, name='dashboard_filter'),
    url(r'dashboard/groups/(?P<group_id>\w+)/users$', views.dashboard_render, name='dashboard_group_users'),
    url(r'dashboard/(?P<question_id>\w+)/users$', views.dashboard_render, name='dashboard_users'),


    # REST API URLS

    url(r'^groups/(?P<group_id>\w+)/answers/useranswers$', csrf_exempt(views.Useranswers.as_view())), # GET
    url(r'^groups/(?P<group_id>\d+)$', csrf_exempt(views.Groups.as_view()), name='group'), # GET, PUT, DELETE
    url(r'^groups$', csrf_exempt(views.Groups.as_view()), name='group_post'), # POST
    url(r'^questions/(?P<question_id>\w+)/SimpleResult$', views.simple_view_answer, name='question_simple_result'), # GET
    url(r'^questions/(?P<question_id>\w+)/ToPrivate$', views.to_private, name='question_to_private'), # GET
    url(r'^questions/(?P<question_id>\w+)$', csrf_exempt(views.Questions.as_view()), name='question'), # GET(full), PUT, DELETE
    url(r'^questions$', csrf_exempt(views.Questions.as_view()), name='question_post'), # POST
    url(r'^questions/(?P<question_id>\w+)/answers/$', csrf_exempt(views.Answers.as_view()), name='answer_post'), # POST, GET, PUT
    url(r'^questions/(?P<question_id>\w+)/answers/(?P<answer_num>\d+)$', csrf_exempt(views.Answers.as_view()), name='answer'), # GET, DELETE
    url(r'^questions/(?P<question_id>\w+)/answers/useranswers/$', csrf_exempt(views.Useranswers.as_view()), name='useranswer'), # GET
    url(r'^questions/(?P<question_id>\w+)/answers/useranswers/(?P<unique_user>\w+)$', csrf_exempt(views.Useranswers.as_view()), name='useranswer'), # GET, DELETE, PUT
    url(r'^questions/(?P<question_id>\w+)/answers/(?P<answer_num>\d+)/useranswers$', csrf_exempt(views.Useranswers.as_view()), name='useranswer_post'), # POST, GET
]

main/models.py
# 직접 개발한 코드
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from hashlib import sha1
from random import randint
from django.conf import settings


class UserManager(BaseUserManager):
    def create_user(self, email, password, **kwargs):
        user = self.model(email=self.normalize_email(email), is_active=True, **kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **kwargs):
        user = self.model(email=self.normalize_email(email), is_staff=True, is_superuser=True, is_active=True, **kwargs)
        user.set_password(password)
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(max_length=250, unique=True)
    username = models.CharField(max_length=250, null=True)

    created_date = models.DateTimeField(auto_now_add=True, null=True)

    is_active = models.NullBooleanField(default=True, null=True)
    is_staff = models.NullBooleanField(default=False, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = UserManager()

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def __str__(self):
        return '[{}]{} ( {} )'.format(self.id, self.email, self.username)

    class Meta:
        swappable = 'AUTH_USER_MODEL'


class ApiKeyManager(models.Manager):

    def _generate_key(self):
        return sha1(str(randint(0, (16 ** 40) - 1)).encode('utf-8')).hexdigest()

    def generate(self, user):
        key = self._generate_key()

        while self.filter(key=key).count() > 0:
            key = self._generate_key()

        return self.create(user=user, key=key)

    def generate_secret(self):
        return self._generate_key()


class ApiKey(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='api_keys')
    key = models.CharField(max_length=40, null=True)
    secret_key = models.CharField(max_length=100, null=True)

    created_dt = models.DateTimeField(auto_now_add=True)

    objects = ApiKeyManager()

    def __str__(self):
        return 'id:{}, {}'.format(self.id, self.key)


class Domain(models.Model):
    api_key = models.ForeignKey(ApiKey, related_name='domains')
    domain = models.CharField(max_length=100)

    created_dt = models.DateTimeField(auto_now_add=True)
    updated_dt = models.DateTimeField(auto_now=True)
    is_removed = models.BooleanField(default=False)

    def __str__(self):
        return '{}'.format(self.domain)

main/forms.py
# 직접 개발한 코드

from django import forms
from main.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _


class UserCreationForm(forms.ModelForm):
    error_messages = {
        'password_mismatch': _("입력한 비밀번호가 같지 않습니다."),
    }
    password1 = forms.CharField(label=_("비밀번호"), widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("비밀번호 확인"), widget=forms.PasswordInput, help_text=_("확인을 위해 입력하신 비밀번호를 다시 입력해주세요."))

    class Meta:
        model = User
        fields = ("email", "username")

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'password']


class AuthenticationFormWithInactiveUsersOkay(AuthenticationForm):
    def confirm_login_allowed(self, user):
        pass

main/views.py
import datetime
from django.core.exceptions import ObjectDoesNotExist
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.cache import cache_page, cache_control, never_cache
from django.views.decorators.csrf import csrf_exempt
from main.forms import UserCreationForm
from main.models import User, ApiKey, Domain

from urllib.parse import urlparse
import json
import jwt


def index(request):
    context = {

    }
    return render(request, 'main/pages/index.html', context)


def user_signup(request):
    context = {

    }
    if request.is_ajax():
        response_data = {}

        data = json.loads(request.body.decode('utf-8'))
        postEmail = data.get('email')
        postUsername = data.get('username')
        postPassword = data.get('password')

        user = User(email=postEmail, username=postUsername)
        user.set_password(postPassword)
        try:
            user.save()

        except IntegrityError as e:
            response_data['status'] = False
            response_data['msg'] = 'Sorry! This email is already signed up.'
            return HttpResponse(json.dumps(response_data),
                                content_type="application/json"
                                )
        response_data['status'] = True
        response_data['msg'] = 'Success!'

        return HttpResponse(
                    json.dumps(response_data),
                    content_type="application/json"
                )


    else:
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                form.save()

        else:
            form = UserCreationForm()

        context.update({'form': form})
        return render(request, 'main/pages/signup.html', context)


def user_login(request):

    context = {}
    response_data = {}
    if request.is_ajax():
        response_data = {}
        data = json.loads(request.body.decode('utf-8'))
        postEmail = data.get('email')
        postPassword = data.get('password')

        try:
            user = authenticate(email=postEmail, password=postPassword)
        except:
            response_data.update({'error': 'no user'})
            return JsonResponse(response_data)

        if user is not None:
                if user.is_active:
                    login(request, user)
                    response_data.update({'status': 'success'})
                    return JsonResponse(response_data)

        return JsonResponse({})


def user_logout(request):
    logout(request)
    return redirect('main:index')

@never_cache
@login_required
def user_mypage(request, id):
    context = {
        'userId': id
    }

    u = User.objects.get(id=id)
    try:
        a = ApiKey.objects.get(user=u)
        d = Domain.objects.filter(api_key=a, is_removed=False)
    except ObjectDoesNotExist:
        a = None
        d = None

    context.update({
        'api_key': a,
        'domains': d
    })
    return render(request, 'main/pages/mypage.html', context)


@login_required
def apikey_new(request):
    context = {}
    if request.method == 'POST':
        ApiKey.objects.generate(request.user)
        return redirect('main:user_mypage', request.user.id)


@login_required
def domain_new(request):
    context = {}
    if request.method == 'POST':
        domain = request.POST.get('domain')
        parsed_domain = urlparse(domain)

        if parsed_domain.path[:9] == '127.0.0.1' or parsed_domain.path[:9] == 'localhost':
            post_domain = parsed_domain.path

        elif parsed_domain.netloc:
            post_domain = parsed_domain.netloc
            if post_domain[:4] == 'www.':
                post_domain = post_domain[4:]
        else:
            post_domain = parsed_domain.path

        # If server can't find a correct URL format
        if not post_domain:
            messages.add_message(request, messages.ERROR, 'Please write a right url.')

        try:
            a = ApiKey.objects.get(key=request.POST.get('api_key'))
        except ObjectDoesNotExist:
            messages.add_message(request, messages.ERROR, 'api key doesn\'t exist.')

        # Check if this user already has the same URL
        try:
            d = Domain.objects.get(domain=post_domain, api_key=a)
        except ObjectDoesNotExist:
            d = Domain(domain=post_domain, api_key=a)
            d.save()
        else:
            messages.add_message(request, messages.ERROR, 'There is already same domain in your account.')

    return redirect('main:user_mypage', request.user.id)


def domain_delete(request):
    response_json = {}
    if request.is_ajax():
        data = json.loads(request.body.decode('utf-8'))
        domain_id = data.get('d_id')

        try:
            domain_instance = Domain.objects.get(id=domain_id)
        except ObjectDoesNotExist:
            response_json.update({
                'status': 'fail'
            })

        domain_instance.is_removed = True
        domain_instance.save()

        response_json.update({
            'status': 'success'
        })

        return JsonResponse(response_json)


def secret_key_new(request, key):
    a = get_object_or_404(ApiKey, key=key)
    a.secret_key = ApiKey.objects.generate_secret()
    a.save()
    return redirect('main:user_mypage', request.user.id)


@csrf_exempt
def jwt_new(request):
    data = json.loads(request.body.decode('utf-8'))
    api_key = data.get('api-key')
    secret = data.get('secret-key')
    exp = data.get('exp')
    nbf = data.get('nbf')
    if not exp:
        exp = datetime.datetime.utcnow() + datetime.timedelta(days=30)
    if not nbf:
        nbf = datetime.datetime.utcnow()

    a = get_object_or_404(ApiKey, key=api_key)
    if a.secret_key == secret:
        encoded = jwt.encode({
            'api-key': api_key,
            'exp': exp,
            'nbf': nbf
        }, secret, algorithm='HS256')

        return JsonResponse({'jwt': str(encoded.decode('utf-8'))})
    else:
        return JsonResponse({'error': 'Not valid secret key.'})


def downloads(request):
    return render(request, 'main/pages/downloads.html')

main/templates/main/pages/apikey_new.html
{% extends 'main/base.html' %}

{% load staticfiles %}

{% block stylesheet %}
    <style>
        .api-key-new-div{
            text-align: center;
        }
    </style>
{% endblock %}
{% block content %}
    <h1>Let's create a new api key.</h1>
    <div class="row api-key-new-div">
        <div class="col-sm-6 col-sm-offset-3">
            <form action="" method="post">
                {% csrf_token %}
                <button class="btn btn-default btn-lg" type="submit">Get my api key</button>
            </form>
        </div>
    </div>

{% endblock %}

{% block script %}{% endblock %}

main/templates/main/pages/footer.html
<footer class="footer">
        <div class="row">
            <div class="footer-nav">
                <div class="col-sm-4">
                    <div class="footer-title">
                        QuesCheetah
                    </div>
                </div>
                <div class="col-sm-2">
                    <p>Sample</p>
                    <div class="footer-elements">
                        <a href="https://mingkim.gitbooks.io/quescheetah-tutorial/content/jekyll.html" target="_blank"><p>Jekyll</p></a>
                        <a href="#"><p>Wordpress</p></a>
                        <a href="#"><p>Tistory</p></a>
                    </div>
                </div>
                <div class="col-sm-2">
                    <p>Documentation</p>
                    <div class="footer-elements">
                        <a href="https://mingkim.gitbooks.io/quescheetah-tutorial/content/overview.html" target="_blank"><p>Overview</p></a>
                        <a href="https://mingkim.gitbooks.io/quescheetah-tutorial/content/js-SDK.html" target="_blank"><p>JavaScript SDK</p></a>
                        <a href="https://mingkim.gitbooks.io/quescheetah-document/content/" target="_blank"><p>REST API</p></a>
                    </div>
                </div>
                <div class="col-sm-2">
                    <p>Pages</p>
                    <div class="footer-elements">
                        <a href="{% url 'v1:dashboard_select' %}"><p>Dashboard</p></a>
                        <a href="{% url 'main:downloads' %}"><p>Downloads</p></a>
                    </div>
                </div>
                <div class="col-sm-2">
                    <p>Contact Us</p>
                    <div class="footer-elements">
                        <a href="https://github.com/mingkim/QuesCheetah" target="_blank"><p>Github</p></a>
                    </div>
                </div>
            </div>
            <div class="footer-license">
                <div class="col-sm-12">
                    QuesCheetah is Free Open Source Software released under the <a href="https://opensource.org/licenses/MIT" target="_blank">MIT</a> License.
                </div>
            </div>
        </div>
</footer>

main/templates/main/pages/mypage.html
{% extends 'main/base.html' %}

{% load staticfiles %}

{% block stylesheet %}
    <style>
        .account-wrapper{
            height: auto;
            width: 770px;
            margin: 0 auto;
            padding: 40px 30px;
            min-height: 300px;
            overflow: hidden;
        }

        .account-wrapper .account-col p{
            border-bottom: solid #cfcfcf 1px;
            height: 50px;
            padding: 14px;
            font-size:15px
        }

        .account-wrapper .account-col p.border-remove{
            border-bottom: none;
        }

        .account-wrapper .account-content p{
            height: 50px;
            padding: 14px;
            font-size:15px
        }

        .account-wrapper .account-content .account-content-jwt{
            height: 150px;
            padding: 14px;
            width: 400px;
        }

        .account-wrapper .account-content .account-content-jwt div{
            margin-bottom: 10px;
        }

        .account-wrapper .account-content .account-content-jwt div div{
            display: inline-block;
            width: 100px;
        }

        .account-wrapper .account-jwt-date{
            display: inline-block;
            width: 180px;
            margin-left: 30px;
        }

        .account-content .account-content-jwt #new-jwt-btn{
            width: 70px;
            margin-left: 240px;
        }

        .account-content .account-apikey-new{
            height: 50px;
            padding: 14px;
        }

        .account-content .account-apikey-new button{
{#            height: 22px;#}
        }


        .account-content .account-url{
            min-height: 200px;
            padding: 14px;
        }

        .account-content .account-url .form-group input{
            width: 90%;
            display: inline-block;
        }

        .domain-delete-btn:hover{
            cursor: pointer;
        }

    </style>
{% endblock %}
{% block content %}
    <div class="row account-info-dev">
        <div class="account-wrapper">
            <div class="account-col col-sm-4">
                <!--<p>Id</p>-->
                <p>Email</p>
                {% if api_key %}
                    <p>Api key</p>
                    <p class="border-remove">Secret key</p>
                    <p></p>
                    <p class="border-remove">Json Web Token</p>
                    <p class="border-remove"></p>
                    <p class="border-remove"></p>
                    <p></p>
                    <p class="border-remove">Authenticated URLs</p>
                {% else %}
                    <p class="border-remove">Api key</p>
                {% endif %}
            </div>
            <div class="account-content col-sm-8">
                <!--<p>{{ userId }}</p>-->
                <p>{{ user.email }}</p>
                {% if api_key %}
                    <p><a href="{% url 'v1:select_question'%}" id="key_value" value="{{ api_key.key }}">{{ api_key.key }}</a></p>
                    <p>
                        <a id="secret_value" value="{{ api_key.secret_key }}">{{ api_key.secret_key }}</a>
                        <a href="{% url 'main:secret_key_new' api_key.key %}"class="btn btn-info">renew</a>
                    </p>
                    <p class="help-block">If secret key is regenerated, prior JWT can not be used.</p>
                    <!--json web token-->
                    <div class="account-content-jwt">
                        <div>
                            <div>Expiration</div>
                            <input type="date" class="account-jwt-date form-control" id="exp">
                        </div>
                        <div>
                            <div>Not before</div>
                            <input type="date" class="account-jwt-date form-control" id="nbf">
                        </div>
                        <a href="" class="btn btn-primary" id="new-jwt-btn">create</a>
                    </div>
                    <p class="help-block" id="jwt-error">Select date properties of your JWT.</p>

                <div class="account-url">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>URL</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for domain in domains %}
                            <tr>
                                <th>{{ forloop.counter }}</th>
                                <th>{{ domain }}</th>
                                <th><span class="domain-delete-btn" d_id="{{ domain.id }}"><i class="fa fa-remove"></i></span></th>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <form class="form" action="/domain/new" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="hidden" value="{{ api_key.key }}" name="api_key">
                            <input type="text" class="form-control" name="domain" placeholder="My domain">
                            <button type="submit" class="btn btn-default">+</button>
                        </div>
                    </form>
                </div>
                <p class="help-block">Set a domain you want to accept in this api key.</p>
                {% else %}
                    <div class="account-apikey-new">
                        <form action="/apikey/new" method="post">
                            {% csrf_token %}
                            <button class="btn btn-success" type="submit">Get my api key</button>
                        </form>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block script %}{% endblock %}

main/templates/main/pages/nav.html
<div class="navbar-back"></div>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'main:index' %}">QuesCheetah</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'main:downloads' %}">Downloads </a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Document <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="https://mingkim.gitbooks.io/quescheetah-tutorial/content/overview.html" target="_blank">Overview</a></li>
                        <li><a href="https://mingkim.gitbooks.io/quescheetah-tutorial/content/js-SDK.html" target="_blank">JavaScript SDK docs</a></li>
                        <li><a href="https://mingkim.gitbooks.io/quescheetah-document/content/" target="_blank">REST API docs</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'v1:dashboard_select' %}">Dashboard</a></li>
                {% if user.is_authenticated %}
                    <li class="login dropdown">
                        <a href="#" class="dropdown-toggle btn" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <p>{{ user.username }}</p>
                            <div class="nav-user-fa">
                                <i class="fa fa-angle-down"></i>
                            </div>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'main:user_mypage' user.id %}">Account</a></li>
                            <li><a href="{% url 'v1:select_question' %}">Questions</a></li>
                            <li><a href="/logout">Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="#" class="btn login" data-toggle="modal" data-target="#myModal">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

main/templates/main/pages/nav_dashboard.html
{% load staticfiles %}
<div class="navbar-back"></div>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'main:index' %}">
                <img src="{% static 'images/qc_logo.png' %}" height="40">
                <p>QuesCheetah</p>
            </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                {% if group_name %}
                    <li><a href="{% url 'v1:dashboard_group_overview' group_id %}">Overview</a></li>
                    <li><a href="{% url 'v1:dashboard_group_filter' group_id %}">Analysis</a></li>
                    <li><a href="{% url 'v1:dashboard_group_users' group_id %}">Users</a></li>
                {% else %}
                    <li><a href="{% url 'v1:dashboard_overview' questions.1.id %}">Overview</a></li>
                    <li><a href="{% url 'v1:dashboard_filter' questions.1.id %}">Analysis</a></li>
                    <li><a href="{% url 'v1:dashboard_users' questions.1.id %}">Users</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="login dropdown">
                        <a href="#" class="dropdown-toggle btn" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <p>{{ user.username }}</p>
                            <div class="nav-user-fa">
                                <i class="fa fa-angle-down"></i>
                            </div>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'main:user_mypage' user.id %}">Account</a></li>
                            <li><a href="{% url 'v1:select_question' %}">Questions</a></li>
                            <li><a href="#">Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="#" class="btn login" data-toggle="modal" data-target="#myModal">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

main/templates/main/pages/nav_dashboard_sample.html
{% load staticfiles %}
<div class="navbar-back"></div>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'main:index' %}">
                <img src="{% static 'images/qc_logo.png' %}" height="40">
                <p>QuesCheetah</p>
            </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'v1:dashboard_sample' 'overview' %}">Overview</a></li>
                <li><a href="{% url 'v1:dashboard_sample' 'filter' %}">Analysis</a></li>
                <li><a href="{% url 'v1:dashboard_sample' 'users' %}">Users</a></li>
            </ul>
        </div>
    </div>
</nav>